### ISSUE TITLE
嵌套在TabBar的自定义NavigationController转场问题

### ISSUE THREAD

**Issue by liwenDeng** [seedante/iOS-ViewController-Transition-Demo#2]
今天在项目中使用自定义Navigation的转场时发现这样一个问题：
如果自定义了NavigationController 转场动画，并且在该NavigationController 外面套了一个TabBarController，在AVC 推到 BVC 过程中，设置 BVC 的 hidesBottomBarWhenPushed = YES 的情况下，tabBar 有一个很明显的滑入画出的动作。如下图，这种情况下应该如何处理？

![tabbartrans](https://cloud.githubusercontent.com/assets/12794697/14736785/474dee2c-08ab-11e6-833e-60729a81b4d7.gif)

**Comment by seedante** [comment]
你是希望这种情况下 TabBar 在 push 前就隐藏？

**Comment by seedante** [comment]
你想获得什么样的结果？

**Comment by liwenDeng** [comment]
我想在转场时 不显示tabBar，已经找到方法了，在转场时设置 tabBar.hidden = YES 既可以了
