### ISSUE TITLE
取消切换失效失效

### ISSUE THREAD

**Issue by ZeroOnet** [seedante/iOS-ViewController-Transition-Demo#5]
![bug](https://cloud.githubusercontent.com/assets/20768739/19344394/9899928c-916c-11e6-821e-52b88d027a0a.gif)

**Comment by ZeroOnet** [comment]
设置了completeSpeed也没有效果，请博主解答！

**Comment by seedante** [comment]
能提供下其他信息吗？我使用同样的模拟器在这个 Demo 下没有复现这个问题。

**Comment by ZeroOnet** [comment]
不好意思啊！我知道是什么问题了！在过渡动画完成的那个block里面我只写了transitionContext.completeTransition(complete)，而实际上在这个Demo中需要在知道是否取消情况下来决定是否完成转场，就像博主写的那样。谢谢！

**Comment by seedante** [comment]
😀
