### ISSUE TITLE
CustomModalTransitionDemo 没有 博文中的效果

### ISSUE THREAD

**Issue by tanpengsccd** [seedante/iOS-ViewController-Transition-Demo#6]
弹出后的PresentView 是全屏
![image](https://cloud.githubusercontent.com/assets/13959880/22853317/3e04b852-f08e-11e6-955e-ee308e062fd3.png)

**Comment by tanpengsccd** [comment]
Xcode 8.2.1
OS X 10.12.3

**Comment by seedante** [comment]
@tanpengsccd 我的疏忽，更新代码时忘记按照文章里的效果来了。稍后更新。

**Comment by seedante** [comment]
@tanpengsccd 已经更新。
